### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ZLDman** [aj-foster/FTCSwitcher#1]
I would like to use a program like this with Windows and OBS.

Are there any plans to make this available for windows users?

If not there any other similar softwares that I could use.

**Comment by aj-foster** [comment]
Hello there 👋🏼 

At the moment, no — I went for a macOS app in Swift because I could build it quickly without worrying about a lot of user interface and similar concerns. With that said, the underlying app is pretty simple: websocket client, a little bit of logic, and calls to the C++ library provided by Blackmagic Design. A node.js script could accomplish the same thing (once you figure out native bindings).

So with that said, while _I_ don't have the time to rewrite the application for Windows, an enterprising programmer could get a proof of concept working pretty quickly.

Concerning OBS, I haven't personally looked into doing that, but given how easy it is to work with OBS using something like a Stream Deck, I suspect it's very doable.

If anyone wants to tackle this project, I will 100% offer advice and encouragement!
